#!/usr/bin/Rscript
library(docopt)
library(cli)
suppressMessages( library(glue) )
suppressMessages( library(tidyverse) )

ps <- cli_process_start; pd <- cli_process_done

'JHU/NYT county-level data combiner

Usage:
  combine-JHU-NYT-counties.R -o <path> --jhu <path> --nyt <path> --metadataJHU <path> --metadataNYT <path> --rejectsJHU <path> --rejectsNYT <path> [--writeRejects <path>] [--writeMetadata <path>]
  combine-JHU-NYT-counties.R (-h | --help)
  combine-JHU-NYT-counties.R --version

Options:
  -o <path>               Path to output joined data to.
  --jhu <path>            Path to cleaned JHU county-level data
  --nyt <path>            Path to cleaned NYT county-level data
  --metadataJHU <path>    Where metadata .json describing JHU data is stored
  --metadataNYT <path>    Where metadata .json describing NYT data is stored
  --rejectsJHU <path>     Path to rejected JHU FIPS [fips, code, reason]
  --rejectsNYT <path>     Path to rejected NYT FIPS [fips, code, reason]
  --writeRejects <path>   Path to output a .csv of rejected FIPS [fips, code, reason] 
  --writeMetadata <path>  Where to write metadata generated by this run
  -h --help               Show this screen.
  --version               Show version.

' -> doc

args <- docopt(doc, version = 'combine-JHU-NYT-counties.R 0.1')

cli_h1("Loading input data")

input_data_spec = cols(
  date = col_date(),
  fips = col_character(),
  cases = col_number(),
  deaths = col_number()
)

ps("Loading JHU case-death data from {.file {args$jhu}}")
jhu <- read_csv(args$jhu, col_types = input_data_spec)
pd()

ps("Loading NYT case-death data from {.file {args$nyt}}")
nyt <- read_csv(args$nyt, col_types = input_data_spec)
pd()

ps("Loading JHU metadata from {.file {args$metadataJHU}}")
metadataJHU <- jsonlite::read_json(args$metadataJHU, simplifyVector = T)
pd()

ps("Loading NYT metadata from {.file {args$metadataNYT}}")
metadataNYT <- jsonlite::read_json(args$metadataNYT, simplifyVector = T)
pd()

ps("Loading JHU rejects .csv from {.file {args$rejectsJHU}}")
rejectsJHU <- read_csv(args$rejectsJHU, col_types = "ccc")
pd()

ps("Loading NYT rejects .csv from {.file {args$rejectsNYT}}")
rejectsNYT <- read_csv(args$rejectsNYT, col_types = "ccc")
pd()

###############
## Checks    ##
###############
cli_h1("ID'ing counties which are unique to NYT")
NYTunique <- full_join(
  count(nyt, fips),
  count(jhu, fips),
  by = 'fips',
  suffix = c('.nyt', '.jhu')
) %>% filter(is.na(n.jhu) & !is.na(n.nyt)) %>% pull(fips)

cli_h3("Unique to NYT:")
cli_ul()
walk(NYTunique, cli_li)
cli_end()

final <- bind_rows(
  jhu,
  filter(nyt, fips %in% NYTunique)
)

cli_h1("Writing outputs")

ps("Writing combined case-death data to {.file {args$o}}")
write_csv(final, args$o)
pd()

if (!is.null(args$writeMetadata)) {
  ps("Writing metadata to {.file {args$writeMetadata}}")
  metadata <- bind_rows(
    metadataJHU,
    filter(metadataNYT, fips %in% NYTunique)
  )
  jsonlite::write_json(metadata, args$writeMetadata)
  pd()

}

if (!is.null(args$writeRejects)) {
  ps("Writing combined rejects to {.file {args$writeRejects}}")
  rejects <- bind_rows(
    rejectsJHU,
    filter(rejectsNYT, !(fips %in% jhu$fips))
  )
  write_csv(rejects, args$writeRejects)
  pd()
}
