#!/usr/bin/Rscript
library(docopt)
library(cli)
suppressMessages( library(tidyverse) )

ps <- cli_process_start; pd <- cli_process_done

'Vaccine imputer and joiner

Usage:
  join-and-impute-vaccines-timeseries.R -o <path> --caseDeathRR <path> --vax <path> --metadata <path> [--writeMetadata <path>]
  join-and-impute-vaccines-timeseries.R (-h | --help)
  join-and-impute-vaccines-timeseries.R --version

Options:
  -o <path>               Path to output joined data to.
  --caseDeathRR <path>    Path to CSV of county-level case,death,rr data
  --vax <path>            Path to Georgetown vaccines data
  --metadata <path>       Where metadata .json describing JHU+NYT data is stored
  --writeMetadata <path>  Where to write metadata generated by this run
  -h --help               Show this screen.
  --version               Show version.

' -> doc

args <- docopt(doc, version = 'join-and-impute-vaccines-timeseries.R 0.1')

cli_h1("Loading input data")

ps("Loading case-death-rr data from {.file {args$caseDeathRR}}")
caseDeathRR <- read_csv(
  args$caseDeathRR,
  col_types = cols(
    date = col_date(),
    fips = col_character(),
    cases = col_number(),
    deaths = col_number(),
    RR = col_number()
  )
)
pd()

ps("Loading Georgetown vaccine data from {.file {args$vax}}")
vax <- read_csv(
  args$vax,
  # Could be replaced with `cols_only()` if we only need a few of these columns
  col_types = cols(
    STATE_NAME  = col_character(),
    STATE       = col_number(),
    COUNTY_NAME = col_character(),
    COUNTY      = col_number(),
    GEOFLAG     = col_character(),
    DATE        = col_date(),
    CASE_TYPE   = col_factor(),
    CASES       = col_number(),
    POPN        = col_number(),
    WEEK        = col_number()
  )
)

# Fix their incorrect treatment of FIPS codes (leading 0 problems)...
# Creates new columns `statefips` and `fips`
vax <- mutate(
  vax,
  # State FIPS area always 2 characters
  statefips = as.character(STATE) %>% ifelse(str_length(.) == 2, ., paste0("0", .)),
  fips = as.character(COUNTY) %>% ifelse(str_length(.) == 5, ., paste0("0", .)),
)
pd()

ps("Loading metadata from {.file {args$metadata}}")
metadata <- jsonlite::read_json(args$metadata, simplifyVector = T)
pd()
        
cli_h1("Imputing")

# Imputing, joining etc
final <- mutate(caseDeathRR, vaccinated = 0)

cli_h1("Writing")

ps("Writing output to {.file {args$o}}")
write_csv(final, args$o)
pd()

if (!is.null(args$writeMetadata)) {
  ps("Writing metadata to {.file {args$writeMetadata}}")
  jsonlite::write_json(metadata, args$writeMetadata)
  pd()
}
